language: python
install: pip install tox
before_script: tox -e flake8
matrix:
  include:
  - env: TOXENV=isort-check
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
script: tox -e $TOXENV